

    upstream nodejs_cluster {
        server app1:3000;
        server app2:3000;
        server app3:3000;
    }

    server {
    listen 443 ssl;
    server_name localhost;
     
    # SSL Termination
    ssl_certificate /etc/nginx/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/nginx-selfsigned.key;	

    location / {
        proxy_pass http://nodejs_cluster;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    }
  
   
    server {
	listen 80;
	server_name localhost;

	location / {
  	    return 301 https://$host$request_uri;
     }

    }

