

    # upstream nodejs_cluster {
    #     server app:3000;
    # }

    # server {
    # listen 443 ssl;
    # server_name localhost;
     
    # # SSL Termination
    # ssl_certificate /etc/nginx/certs/nginx-selfsigned.crt;
    # ssl_certificate_key /etc/nginx/certs/nginx-selfsigned.key;	

    # location / {
    #     proxy_pass http://nodejs_cluster;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    # }
    # }
  
   
    # server {
	# listen 80;
	# server_name localhost;

	# location / {
  	#     return 301 https://$host$request_uri;
    #  }

    # }

upstream nodejs_cluster {
    server app:3000;
}

server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://nodejs_cluster;
        
        # CRITICAL FOR PAYSTACK SIGNATURE MATCHING:
        # Ngrok changes the 'Host' header to the xxxx.ngrok-free.app address. 
        # We need to pass the real host forward down into the Node app.
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Ensure Nginx doesn't buffer or alter the body chunks
       proxy_pass_request_headers on;
    }
}