name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install and test
        run: |
          npm ci
          npm test
      - uses: mr-smithers-excellent/docker-build-push@v7
        name: Build & push Docker image
        with:
          image: chusvybe/cozy
          tags: v1, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}